### Load tensorflow

In [29]:
import tensorflow as tf

### Collect Data

In [30]:
(trainX, trainY),(testX, testY) = tf.keras.datasets.mnist.load_data()

In [31]:
trainX.shape

(60000, 28, 28)

In [32]:
trainY.shape

(60000,)

In [33]:
testX.shape

(10000, 28, 28)

In [34]:
testY.shape

(10000,)

In [35]:
trainX[0]
#zeros indicates white spaces b/w image

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [36]:
print(testY[0:5])

[7 2 1 0 4]


### Convert Output label to multiple values

In [37]:
trainY = tf.keras.utils.to_categorical(trainY, num_classes=10)
testY = tf.keras.utils.to_categorical(testY, num_classes=10)

In [41]:
trainY

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [42]:
testY

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [43]:
print(trainY.shape)
print('first 2 examples now are:' , trainY[0:2])

(60000, 10)
first 2 examples now are: [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# BUILDING MODEL

In [38]:
#Intialize Sequential model
model = tf.keras.models.Sequential()
#reshaping data (rearranging the data into the eqn from metrix) 2D to !D
#lossing positional infomation for reshaping 
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))
#normalizing the data 
model.add(tf.keras.layers.BatchNormalization())
#Adding dense layers 
model.add(tf.keras.layers.Dense(10,activation='softmax'))
#complie model 
#categorical_crossentropy for classification problems
model.compile(optimizer='sgd',loss='categorical_crossentropy',metrics=['accuracy'])

In [39]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape_2 (Reshape)         (None, 784)               0         
                                                                 
 batch_normalization_4 (Batc  (None, 784)              3136      
 hNormalization)                                                 
                                                                 
 dense_6 (Dense)             (None, 10)                7850      
                                                                 
Total params: 10,986
Trainable params: 9,418
Non-trainable params: 1,568
_________________________________________________________________


In [46]:
model.fit(trainX,trainY,validation_data=(testX,testY),
          epochs=100,batch_size=trainX.shape[0])
#all the data is given
#loss&acc are belong to train data 
#val_loss&val_acc belongs to test data

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 0.2809 - accuracy: 0.9245 - val_loss: 0.3568 - val_accuracy: 0.9207
Epoch 2/100
1/1 [==============================] - 1s 904ms/step - loss: 0.2808 - accuracy: 0.9245 - val_loss: 0.3491 - val_accuracy: 0.9208
Epoch 3/100
1/1 [==============================] - 1s 937ms/step - loss: 0.2808 - accuracy: 0.9245 - val_loss: 0.3446 - val_accuracy: 0.9207
Epoch 4/100
1/1 [==============================] - 1s 971ms/step - loss: 0.2807 - accuracy: 0.9246 - val_loss: 0.3415 - val_accuracy: 0.9206
Epoch 5/100
1/1 [==============================] - 1s 896ms/step - loss: 0.2806 - accuracy: 0.9246 - val_loss: 0.3391 - val_accuracy: 0.9206
Epoch 6/100
1/1 [==============================] - 1s 865ms/step - loss: 0.2806 - accuracy: 0.9246 - val_loss: 0.3371 - val_accuracy: 0.9206
Epoch 7/100
1/1 [==============================] - 1s 920ms/step - loss: 0.2805 - accuracy: 0.9247 - val_loss: 0.3354 - val_accuracy: 0.9207
Epoch 8/100
1/1 

In [47]:
#using batch size = 40
model.fit(trainX,trainY,validation_data=(testX,testY),epochs=10,batch_size=40)
#40 records at a time
#for getting beter accuracy we use batch size

Epoch 1/10
1500/1500 [==============================] - 9s 6ms/step - loss: 0.2944 - accuracy: 0.9166 - val_loss: 0.3386 - val_accuracy: 0.9209
Epoch 2/10
1500/1500 [==============================] - 10s 6ms/step - loss: 0.2929 - accuracy: 0.9170 - val_loss: 0.3760 - val_accuracy: 0.9200
Epoch 3/10
1500/1500 [==============================] - 10s 7ms/step - loss: 0.2901 - accuracy: 0.9179 - val_loss: 0.4109 - val_accuracy: 0.9201
Epoch 4/10
1500/1500 [==============================] - 10s 7ms/step - loss: 0.2894 - accuracy: 0.9183 - val_loss: 0.3678 - val_accuracy: 0.9187
Epoch 5/10
1500/1500 [==============================] - 8s 5ms/step - loss: 0.2891 - accuracy: 0.9175 - val_loss: 0.3461 - val_accuracy: 0.9203
Epoch 6/10
1500/1500 [==============================] - 8s 5ms/step - loss: 0.2880 - accuracy: 0.9183 - val_loss: 0.3874 - val_accuracy: 0.9201
Epoch 7/10
1500/1500 [==============================] - 10s 7ms/step - loss: 0.2857 - accuracy: 0.9187 - val_loss: 0.3754 - val_accur

# NEURAL NETWORKS

In [59]:
!pip install ann_visualizer
!pip install graphviz

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for ann_visualizer: filename=ann_visualizer-2.5-py3-none-any.whl size=4181 sha256=dddd115762ab98c81b4ad5f39466787a9275d88fdfe5efad812c1ba46753a16f
  Stored in directory: c:\users\priyanka\appdata\local\pip\cache\wheels\d3\3c\ab\2ffe5e9f68c95fcee1eb80deadd2316e8311ce1b7e5fabfe9c
Successfully built ann_visualizer
     -------------------------------------- 47.0/47.0 kB 465.8 kB/s eta 0:00:00


In [48]:
#Initialize Sequential model
model = tf.keras.models.Sequential()
#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))
#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

# ADDING HIDDEN LAYERS

In [49]:
#Add 1st hidden layer
model.add(tf.keras.layers.Dense(200, activation='relu'))

In [50]:
#Add 2nd hidden layer
model.add(tf.keras.layers.Dense(100, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [51]:
#Add 3rd hidden layer
model.add(tf.keras.layers.Dense(60, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [52]:
#Add 4th hidden layer
model.add(tf.keras.layers.Dense(30, activation='relu'))

In [53]:
#Add OUTPUT layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))

## model building

In [54]:
#Create optimizer with non-default learning rate
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03, decay=0.001)
#Compile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

C:\Users\Priyanka\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\gradient_descent.py:111: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


## Review model

In [55]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape_3 (Reshape)         (None, 784)               0         
                                                                 
 batch_normalization_5 (Batc  (None, 784)              3136      
 hNormalization)                                                 
                                                                 
 dense_7 (Dense)             (None, 200)               157000    
                                                                 
 dense_8 (Dense)             (None, 100)               20100     
                                                                 
 batch_normalization_6 (Batc  (None, 100)              400       
 hNormalization)                                                 
                                                                 
 dense_9 (Dense)             (None, 60)               

## Train the model

In [58]:
model.fit(trainX,trainY,          
          validation_data=(testX,testY),epochs=5,batch_size=40)

Epoch 1/5
1500/1500 [==============================] - 18s 12ms/step - loss: 0.0626 - accuracy: 0.9812 - val_loss: 0.2446 - val_accuracy: 0.9637
Epoch 2/5
1500/1500 [==============================] - 18s 12ms/step - loss: 0.0604 - accuracy: 0.9813 - val_loss: 0.3130 - val_accuracy: 0.9648
Epoch 3/5
1500/1500 [==============================] - 16s 11ms/step - loss: 0.0605 - accuracy: 0.9815 - val_loss: 0.2323 - val_accuracy: 0.9650
Epoch 4/5
1500/1500 [==============================] - 17s 11ms/step - loss: 0.0597 - accuracy: 0.9817 - val_loss: 0.2242 - val_accuracy: 0.9641
Epoch 5/5
1500/1500 [==============================] - 19s 13ms/step - loss: 0.0601 - accuracy: 0.9814 - val_loss: 0.1840 - val_accuracy: 0.9633


# MODEL PREDICITIONS

In [70]:
#Save the model in current directory
model.save('mnist_dnn_v1.h5')

In [71]:
#Load the model in memory
model = tf.keras.models.load_model('mnist_dnn_v1.h5')

In [76]:
#Review the model (optional)
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 128)               100480    
                                                                 
 dense_13 (Dense)            (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [89]:
#What should be the shape of model input
model.input

<KerasTensor: shape=(None, 784) dtype=float32 (created by layer 'dense_16_input')>

In [74]:
#Shape of each example in test dataset
testX[0].shape

(28, 28)

In [78]:
#Make it 3 dimension data
import numpy as np
input_data = np.expand_dims(testX[0], axis=0)
input_data.shape

(1, 28, 28)

In [94]:
input_data = input_data.reshape(-1, 784)

In [95]:
#Model prediction
pred = model.predict(input_data)
pred

1/1 [==============================] - 0s 144ms/step


array([[6.6239342e-02, 0.0000000e+00, 0.0000000e+00, 1.9194131e-09,
        1.0153263e-11, 1.4803819e-23, 0.0000000e+00, 2.3395722e-01,
        0.0000000e+00, 6.9980341e-01]], dtype=float32)

In [96]:
#Model prediction shape
pred.shape

(1, 10)

In [97]:
#Model prediction for first example
pred[0]

array([6.6239342e-02, 0.0000000e+00, 0.0000000e+00, 1.9194131e-09,
       1.0153263e-11, 1.4803819e-23, 0.0000000e+00, 2.3395722e-01,
       0.0000000e+00, 6.9980341e-01], dtype=float32)

In [98]:
#Find the index of highest probability value
np.argmax(pred[0])

9

In [99]:
#Actual label
np.argmax(testY[0])

7

In [118]:
testY[0].shape

(10,)